auth-stuff
Kyoso-Team/kyoso pull request #3
Opened 2024-12-30 20:57 UTC by artemosuskyi

- Added changing discord accounts endpoint
- Added refresh token endpoint for osu and discord tokens

2025-02-13 16:26 UTC, L-Mario564 requested changes

2025-02-13 16:26 UTC, L-Mario564 commented on backend/src/routers/auth.ts
> +    '/callback/discord/change',
Could you add `redirect_path` as an optional query param so we can redirect users to the page they were in prior to making this request? (Something similar is implemented for `/login`).

2025-02-13 16:26 UTC, L-Mario564 commented on backend/src/routers/auth.ts
> +    ]);
We only want to refresh the tokens and update the user if the tokens are expired. I believe osu! tokens expire first, in 24 hours, so compare `tokenIssuedAt` with the current time to see if they need updating or not.

2025-02-15 19:09 UTC, artemosuskyi commented on backend/src/routers/auth.ts
> +    ]);
Should we just send 204 with like "no updates needed" if both are still valid?

2025-02-15 19:52 UTC, artemosuskyi commented on backend/src/routers/auth.ts
> +    ]);
To be honest I can't see any harm in refreshing tokens preemptively, considering this endpoint should be sort of auto-triggering when the token is actually invalid or something

2025-03-03 22:14 UTC, L-Mario564 approved these changes

2025-03-03 22:14 UTC, merged